# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm audit
    - run: npm run build --if-present
    - env:
        NODE12_TOKEN: ${{ secrets.NODE12_TOKEN }}
        NODE14_TOKEN: ${{ secrets.NODE14_TOKEN }}
        NODE15_TOKEN: ${{ secrets.NODE15_TOKEN }}
        NODE16_TOKEN: ${{ secrets.NODE16_TOKEN }}
      run: npm test
